on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

name: Create Release Draft

jobs:
  build:
    name: Create Release Asset
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build project
        run: |
          sudo apt-get install podman
          yarn run yarn:restore
          yarn run podman --lint=immutable --zip

      - name: Draft Release
        id: draft_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Package
        id: upload-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ./build/io.github.mreditor.gnome-shell-extensions.scroll-panel.zip
          asset_name: io.github.mreditor.gnome-shell-extensions.scroll-panel_${{ github.ref }}.zip
          asset_content_type: application/zip
